# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 155f0310f70a7af2f62126dad519048b04b05e0f036d1dc8a152d3a0a55fc5fdfb8d0ffb0f47ca63a48181c2a18e134ab57166c1695b7f07f3d4eec56dfc2965

test:
  secret_key_base: 752fe84023847de5dd2353340902b3f5771d50bedcd90200b42f948e75b06522127abe8c24b37e73adacb5aaf61da95bd143e1ce140ce18b9c780f2514b99d3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
